### PR TITLE
fix(dht): Lan discovery permission denied

### LINKED ISSUE #76: Lan Discovery segfault
When running `$ cargo run --example dht_node`

```
Starting program: /home/humbug/zetox/target/debug/examples/dht_node 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff69ff700 (LWP 25611)]
[New Thread 0x7ffff63ff700 (LWP 25612)]
[New Thread 0x7ffff5dff700 (LWP 25613)]
[New Thread 0x7ffff57ff700 (LWP 25614)]
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([125, 237, 186, 21, 65, 189, 85, 24, 226, 60, 155, 217, 29, 118, 253, 5, 234, 67, 113, 199, 74, 13, 217, 251]), payload: [231, 125, 48, 121, 172, 244, 85, 240, 54, 170, 147, 106, 183, 87, 71, 69, 128, 26, 136, 200, 225, 140, 143, 26, 216, 151] })
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([139, 241, 179, 179, 95, 133, 79, 59, 229, 252, 46, 221, 122, 137, 147, 157, 216, 65, 94, 219, 204, 64, 143, 160]), payload: [215, 123, 23, 74, 183, 63, 237, 66, 78, 129, 78, 192, 192, 112, 250, 21, 104, 197, 20, 103, 168, 32, 50, 159, 139, 255] })
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([40, 29, 28, 143, 170, 224, 191, 18, 6, 16, 7, 201, 203, 180, 240, 78, 11, 57, 173, 78, 85, 56, 195, 136]), payload: [87, 64, 179, 28, 187, 46, 104, 118, 191, 40, 161, 20, 177, 51, 213, 26, 148, 60, 216, 224, 132, 16, 13, 45, 119, 5] })
lan_wakeup

Thread 4 "tokio-runtime-w" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5dff700 (LWP 25613)]
0x00005555557e8e03 in get_if_addrs::getifaddrs_posix::sockaddr_to_ipaddr::haaf65eefab8dbaee (sockaddr=0x0)
    at /home/humbug/.cargo/registry/src/github.com-1ecc6299db9ec823/get_if_addrs-0.5.0/src/lib.rs:163
163	        let sa_family = u32::from(unsafe { *sockaddr }.sa_family);
```

```
   │130         // get broadcast addresses for host's network interfaces                                                   │
   │131         fn get_ipv4_broadcast_addrs() -> Vec<IpAddr> {                                                             │
  >│132             let ifs = get_if_addrs::get_if_addrs().expect("no network interface");                                 │
   │133             ifs.iter().filter_map(|interface|                                                                      │
   │134                 match interface.addr {                                                                             │
   │135                     IfAddr::V4(ref addr) => addr.broadcast,                                                        │
   │136                     _ => None,                                                                                     │
   │137             })                                                                                                     │
   │138             .map(|ipv4|                                                                                            │
   │139                 IpAddr::V4(ipv4)                                                                                   │
   │140             ).collect()                                                                                            │
   │141         }       
```

### PR DESCRIPTION
**Pull request by NamsooCho**
The reason of error is socket does not have right to send broadcast addresses.

TODO:

- [x] Send ipv4 broadcast if socket listens to ipv4 only
- [x] Send ipv6 broadcast if socket listens to ipv6 only

Closes #76

Socket can listen both ipv4 and ipv6 at the same time.
But socket can send packet only one ip-type.

so listening on both type.
separated socket is used to send packet.

### CODE REVIEW

File: src/toxcore/dht/client.rs [hunk 1]
```diff
@@ -150,10 +150,10 @@ impl Client {
         res.push(
             ("255.255.255.255").parse().unwrap()
         );
-        // Ipv6 broadcast address
-        res.push(
-            ("FF02::1").parse().unwrap()
-        );
+        // TODO: Ipv6 broadcast address
```
Comment (kpp) [inline src/toxcore/dht/client.rs]: Why did you remove ipv6 addr?

Comment (NamsooCho) [reply src/toxcore/dht/client.rs]: In dht_node.rs(example) there is no binding socket for IPv6.
So Ipv6 packet can't be sent using Ipv4 socket.

**Comment by kpp** [comment]
It worked, thanks. Maybe we should move to another library without segfaults in it?

**Comment by NamsooCho** [comment]
Yes. I will search another library supporting both unix and windows.

File: src/toxcore/dht/client.rs (hunk 1 above)
Comment (kurnevsky) [reply src/toxcore/dht/client.rs]: As I see in LAN_Discovery.c#380 they check type of socket and then send packet to the right address.

Comment (kurnevsky) [reply src/toxcore/dht/client.rs]: btw, they use IPv4-in-IPv6 to send to IPv4 broadcast address if socket is IPv6.

File: src/toxcore/dht/client.rs [hunk 2]
```diff
@@ -135,25 +135,51 @@ impl Client {
...
-        .map(|ipv4|
-            IpAddr::V4(ipv4)
-        ).collect()
+        .map(|addr|
+            IpAddr::V4(addr)
+        )
+        .collect()
+    }
+    // get broadcast addresses for host's network interfaces
+    fn get_ipv6_broadcast_addrs() -> Vec<IpAddr> {
```
Comment (kurnevsky) [inline src/toxcore/dht/client.rs]: Is it possible that IPv6 has broadcast address? According to wiki:
> Internet Protocol version 6 (IPv6), the next generation Internet Protocol, does not implement the method of broadcast, and therefore does not define broadcast addresses.

File: src/toxcore/dht/client.rs [hunk 3]
```diff
@@ -135,25 +135,51 @@ impl Client {
...
+        // If ipv4 only, broadcast to only Ipv4
+        // If ipv6 only, braodcast to only Ipv6
+        // If both, braodcast to both addresses
+        let ips = Client::get_ipv4_broadcast_addrs();
+        res.extend(ips.iter());
+
+        let ips = Client::get_ipv6_broadcast_addrs();
+        res.extend(ips.iter());
+
+        if !res.iter().filter(|ip| ip.is_ipv4()).next().is_none() {
```
Comment (kurnevsky) [inline src/toxcore/dht/client.rs]: It seems to me it's not the right way to check type of broadcast address. It should depend on socket type.

File: examples/dht_node.rs [hunk 4]
```diff
@@ -98,10 +117,14 @@ fn main() {
 
     let writer = rx
         .map_err(|_| Error::new(ErrorKind::Other, "rx error"))
-        .fold(sink, move |sink, packet| {
+        .fold(sink, move |_sink, packet| {
             // println!("send = {:?}", packet.clone());
             debug!("Send {:?} => {:?}", packet.0, packet.1);
-            sink.send(packet)
+            if packet.1.is_ipv4() {
```
[the remark this answers is not in the document]
Comment (NamsooCho) [reply examples/dht_node.rs]: In C toxcore, sending ipv4 packet using ipv6 socket is done using sendto() function.
But, our Rust implementation uses DhtCodec and (Sink, Stream) pair.
I can't find the Rust function equivalent to send_to() In C.

File: src/toxcore/dht/client.rs (hunk 3 above)
Comment (NamsooCho) [reply src/toxcore/dht/client.rs]: Yes. you are right.
Toxcore runs as Ipv4 or ipv6 mode, do not run as both mode at the same time.

File: src/toxcore/dht/client.rs (hunk 2 above)
Comment (NamsooCho) [reply src/toxcore/dht/client.rs]: Yes, but FF02::01 is used for broadcasting.

File: examples/dht_node.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (NamsooCho) [reply examples/dht_node.rs]: sendto() can send ipv4 packet at socket mode is ipv6.

File: src/toxcore/dht/client.rs (hunk 2 above)
Comment (kurnevsky) [reply src/toxcore/dht/client.rs]: FF02::01 is a multicast address for all nodes in local network.
They just set netmask in broadcast field in case of ipv6:
https://github.com/maidsafe/get_if_addrs/blob/master/src/lib.rs#L259
It seems to me it's not correct to use it as broadcast address.

Comment (NamsooCho) [reply src/toxcore/dht/client.rs]: Yes. we are saying same thing.
Lan Discovery is for local network.

Comment (NamsooCho) [reply src/toxcore/dht/client.rs]: this function is given by crate named "get_if_addrs".
I guess that this function may return FF02::01.

File: examples/dht_node.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (kurnevsky) [reply examples/dht_node.rs]: But why not just sink.send(packet)? Anyway ipv4 address can be converted to ipv6 address using IPv4-in-IPv6 mapping.

[the remark this answers is not in the document]
Comment (NamsooCho) [reply examples/dht_node.rs]: Yes.
Now, I found some way.
I will push my new way.
Please review this push.

File: src/toxcore/dht/client.rs (hunk 2 above)
Comment (kurnevsky) [reply src/toxcore/dht/client.rs]: See sorce code: https://github.com/maidsafe/get_if_addrs/blob/master/src/lib.rs#L259
It will return netmasks (I suppose ffff:ffff:ffff:ffff::).

Comment (NamsooCho) [reply src/toxcore/dht/client.rs]: Thanks for your comments.
I will revise code on this.

File: examples/dht_node.rs [hunk 5]
```diff
@@ -98,10 +100,13 @@ fn main() {
...
-        .fold(sink, move |sink, packet| {
+        .fold(sink, move |sink, (packet, mut addr)| {
             // println!("send = {:?}", packet.clone());
-            debug!("Send {:?} => {:?}", packet.0, packet.1);
-            sink.send(packet)
+            debug!("Send {:?} => {:?}", packet, addr);
+            if let IpAddr::V4(ip) = addr.ip() {
+                addr = SocketAddr::new(IpAddr::V6(ip.to_ipv6_mapped()), 33445);
+            }
+            sink.send((packet, addr))
```
Comment (kurnevsky) [inline examples/dht_node.rs]: What happens if you just send to ipv4 address? Shouldn't tokio take care of this conversion?

Comment (NamsooCho) [reply examples/dht_node.rs]: Now, dht_node run as a ipv6 mode.
If target addr is ipv4, then convert it's address to ipv6 format.

Comment (kurnevsky) [reply examples/dht_node.rs]: Yes, I got it. But why you do it manually? Will it fail otherwise?

Comment (NamsooCho) [reply examples/dht_node.rs]: As I know, it fails with message "Invalid argument"

File: src/toxcore/dht/client.rs [hunk 6]
```diff
@@ -135,30 +135,38 @@ impl Client {
...
+            res.push(
+                ("::1").parse().unwrap() // my LAN config has no route to address of FF02::1
+            );
+        }
         res
     }
     /// send LanDiscovery packets to broadcast addresses
-    pub fn send_lan_discovery(&self) -> IoFuture<()> {
-        let ip_addrs = Client::get_broadcast_addresses();
+    pub fn send_lan_discovery(&self, sock_family: u8) -> IoFuture<()> {
```
Comment (kpp) [inline src/toxcore/dht/client.rs]: as I told you before, there should be 2 methods: `send_lan_discovery_ipv4` and `send_lan_discovery_ipv6`. Based on the address it is examples/dht_node responsibility to send correct packet. You must not add a new flag and keep it inside Server

**Comment by NamsooCho** [comment]
pushed just before

File: src/toxcore/dht/client.rs [hunk 7]
```diff
@@ -135,30 +135,35 @@ impl Client {
...
+            ["255.255.255.255".parse().unwrap()].iter()
         );
-        // Ipv6 broadcast address
-        res.push(
-            ("FF02::1").parse().unwrap()
+        let lan_packet = DhtPacket::LanDiscovery(LanDiscovery {
+            pk: self.pk,
+        });
+        let lan_sender = ip_addrs.iter().map(|&addr|
+            self.send_to(SocketAddr::new(addr, 33445), lan_packet.clone())
```
Comment (kpp) [inline src/toxcore/dht/client.rs]: Add doc that 33445 is hardcoded by default

File: src/toxcore/dht/server.rs [hunk 8]
```diff
@@ -422,13 +422,22 @@ impl Server {
...
         let client = self.create_client(&addr, self.pk);
-        client.send_lan_discovery()
+        client.send_lan_discovery_ipv4()
+    }
+    /**
+    send LanDiscovery packet to all broadcast addresses when dht_node runs as ipv6 mode
+    */
+    pub fn send_lan_discovery_ipv6(&self) -> IoFuture<()> {
+        // addr is dummy, actual lan discovery packet sending logic exists in client
+        let addr: SocketAddr = "127.0.0.1:33445".parse().unwrap();
```
Comment (kpp) [inline src/toxcore/dht/server.rs]: Really 127.0.0.1 for ipv6?

File: examples/dht_node.rs [hunk 9]
```diff
@@ -98,10 +102,15 @@ fn main() {
...
         .map_err(|_| Error::new(ErrorKind::Other, "rx error"))
-        .fold(sink, move |sink, packet| {
+        .fold(sink, move |sink, (packet, mut addr)| {
             // println!("send = {:?}", packet.clone());
-            debug!("Send {:?} => {:?}", packet.0, packet.1);
-            sink.send(packet)
+            debug!("Send {:?} => {:?}", packet, addr);
+            if local.is_ipv6() {
+                if let IpAddr::V4(ip) = addr.ip() {
+                    addr = SocketAddr::new(IpAddr::V6(ip.to_ipv6_mapped()), 33445);
```
Comment (kurnevsky) [inline examples/dht_node.rs]: Maybe use addr.port() instead of hardcoded 33445?

File: examples/dht_node.rs [hunk 10]
```diff
@@ -84,7 +88,7 @@ fn main() {
     // incoming packet.
     let server_obj_c = server_obj.clone();
     let handler = stream.for_each(move |(packet, addr)| {
-        println!("recv = {:?}", packet.clone());
+        //println!("recv = {:?}", packet.clone());
```
Comment (kpp) [inline examples/dht_node.rs]: don't comment this line

File: src/toxcore/dht/server.rs [hunk 11]
```diff
@@ -896,26 +900,6 @@ mod tests {
             }
         }).collect().wait().unwrap();
     }
-    // send_ping_req()
-    #[test]
```
Comment (kpp) [inline src/toxcore/dht/server.rs]: Why did you remove the test?

File: examples/dht_node.rs (hunk 10 above)
Comment (NamsooCho) [reply examples/dht_node.rs]: send_ping_req() is moved into send_pings() to avoid deadlock

File: src/toxcore/dht/server.rs (hunk 11 above)
Comment (NamsooCho) [reply src/toxcore/dht/server.rs]: send_ping_req() is moved into send_pings() to avoid deadlock

File: src/toxcore/dht/client.rs [hunk 12]
```diff
@@ -135,35 +135,40 @@ impl Client {
...
     }
-    /// send LanDiscovery packets to broadcast addresses
-    pub fn send_lan_discovery(&self) -> IoFuture<()> {
-        let ip_addrs = Client::get_broadcast_addresses();
+    /// send LanDiscovery packets to broadcast addresses when dht_node runs as Ipv6 mode
+    pub fn send_lan_discovery_ipv6(&self) -> IoFuture<()> {
+        let mut ip_addrs = Client::get_ipv4_broadcast_addrs();
+        // Ipv6 broadcast address
+        ip_addrs.push(
+            "::1".parse().unwrap() // it should be FF02::1, but for now, my LAN config has no route to address of FF02::1
```
Comment (kurnevsky) [inline src/toxcore/dht/client.rs]: c-toxcore in case of IPv6 sends packet to one more address - 255.255.255.255 mapped to IPv6. Maybe we should add it?

File: src/toxcore/dht/client.rs [hunk 13]
```diff
@@ -135,35 +135,44 @@ impl Client {
...
+        );
+        // Ipv4 global broadcast address
+        ip_addrs.push(
+            "255.255.255.255".parse().unwrap()
```
Comment (kpp) [inline src/toxcore/dht/client.rs]: Make it ipv6 mapped

Comment (kpp) [reply src/toxcore/dht/client.rs]: For example, ::ffff:192.0.2.128 represents the IPv4 address 192.0.2.128.

File: src/toxcore/dht/client.rs [hunk 14]
```diff
@@ -135,35 +135,44 @@ impl Client {
...
     }
-    /// send LanDiscovery packets to broadcast addresses
-    pub fn send_lan_discovery(&self) -> IoFuture<()> {
-        let ip_addrs = Client::get_broadcast_addresses();
+    /// send LanDiscovery packets to broadcast addresses when dht_node runs as Ipv6 mode
+    pub fn send_lan_discovery_ipv6(&self) -> IoFuture<()> {
+        let mut ip_addrs = Client::get_ipv4_broadcast_addrs();
+        // Ipv6 broadcast address
+        ip_addrs.push(
+            "::1".parse().unwrap() // it should be FF02::1, but for now, my LAN config has no route to address of FF02::1
```
Comment (kpp) [inline src/toxcore/dht/client.rs]: Write comment as TODO

File: src/toxcore/dht/server.rs (hunk 11 above)
Comment (kpp) [reply src/toxcore/dht/server.rs]: OK
